[tool.poetry]
name = "templating-client-py"
version = "1.0.0"
description = "Client for templating microservice"
authors = ["Tiago Santos <tiago.santos@vizidox.com>", "Joana Teixeira <joana.teixeira@vizidox.com"]

[tool.poetry.dependencies]
python = "^3.7"

requests="2.22.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
