# Required metadata
sonar.projectName=plato-helper-py
sonar.organization=morphotech
sonar.projectKey=Morphotech_plato-helper-py

sonar.sources=plato_helper_py/
sonar.tests=tests/
sonar.python.coverage.reportPaths=coverage/coverage.xml
sonar.python.version=3.9,3.10,3.11,3.12,3.13,3.14

# Language
sonar.language=python
# Encoding of sources files
sonar.sourceEncoding=UTF-8